baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "itsrounak"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "blog"
    url = "/blog/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "projects"
    url = "/projects/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "about"
    url = "/about/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/itsrounak"
    title = "GitHub"
    weight = 6
  [[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-fw'></i>"
    post = ""
    name = ""
    url = "https://linkedin.com/in/rounak-agarwal-941a46aa"
    title = "GitHub"
    weight = 8


    # site description
    description = "About Rounak"
    # site keywords
    keywords = ["Rounak", "Profile"]

[params.search]
    enable = false
    # type of search engine ("lunr", "algolia")
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

    # Home page config
    [params.home]
      # amount of RSS pages
      rss = 10
      # Home page profile
      [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/memoji_mac.jpeg"
      # title shown in home page (HTML format is supported)
      title = "Rounak Agarwal"
      # subtitle shown in home page
      subtitle = "Hey!        I am Rounak Agarwal!"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "I am a junior or a first-year Computer Science student, majoring in Data Science at Monash University, Australia.This websites serve as my garden of thoughts - a collection of things that I have learned over the years.I write blog posts ocasionally. I will graduate in 2023. Feel free to have a glance over my projects accomplished, read my blog or learn more about me."

      # Home page posts
      [params.home.posts]
        enable = true
        # special amount of posts in each home posts page
        paginate = 6

      # Social config in home page
      [languages.en.params.social]
        GitHub = "itsrounak"
        Linkedin = "rounak-agarwal-941a46aa"
        Twitter = "rounak_agarwall"
        Instagram = "rounak_agarwall"
        Facebook = "rounak.agarwal.58173"
        Telegram = ""
        Medium = ""
        Gitlab = ""
        Youtubelegacy = ""
        Youtubecustom = ""
        Youtubechannel = ""
        Tumblr = ""
        Quora = ""
        Keybase = ""
        Pinterest = ""
        Reddit = ""
        Codepen = ""
        FreeCodeCamp = ""
        Bitbucket = ""
        Stackoverflow = ""
        Weibo = ""
        Odnoklassniki = ""
        VK = ""
        Flickr = ""
        Xing = ""
        Snapchat = ""
        Soundcloud = ""
        Spotify = ""
        Bandcamp = ""
        Paypal = ""
        Fivehundredpx = ""
        Mix = ""
        Goodreads = ""
        Lastfm = ""
        Foursquare = ""
        Hackernews = ""
        Kickstarter = ""
        Patreon = ""
        Steam = ""
        Twitch = ""
        Strava = ""
        Skype = ""
        Whatsapp = "+61426254728"
        Zhihu = ""
        Douban = ""
        Angellist = ""
        Slidershare = ""
        Jsfiddle = ""
        Deviantart = ""
        Behance = ""
        Dribbble = ""
        Wordpress = ""
        Vine = ""
        Googlescholar = ""
        Researchgate = ""
        Thingiverse = ""
        Devto = ""
        Gitea = ""
        XMPP = ""
        Matrix = ""
        Bilibili = ""
        Email = "rounak.agarwal14@gmail.com"
        RSS = true



      # Header config
      # 页面头部导航栏配置
     [params.header]
       # desktop header mode ("fixed", "normal", "auto")
       # 桌面端导航栏模式 ("fixed", "normal", "auto")
       desktopMode = "fixed"
       # mobile header mode ("fixed", "normal", "auto")
       # 移动端导航栏模式 ("fixed", "normal", "auto")
       mobileMode = "auto"
       # Header title config
       # 页面头部导航栏标题配置
       [params.header.title]
         # URL of the LOGO
         # LOGO 的 URL
         logo = "/images/memoji_mac.jpeg"
      # title name
         # 标题名称
         name = "itsrounak"
         # you can add extra information before the name (HTML format is supported), such as icons
         # pre = "<i class='far fa-kiss-wink-heart fa-fw'></i>" 

  # Footer config
  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2020
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Cookie consent config
  # Cookie 许可配置
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

# Markup related configuration in Hugo
# Hugo 解析文档的配置

  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
# 作者配置
[author]
  name = "Rounak Agarwal"
  email = "rounak.agarwal14@gmail.com"
  link = "/about"

# Sitemap config
# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
